import {
  Treatment,
  Doctor,
  Review,
  GalleryItem,
  ClinicSettings,
  Appointment,
  Patient,
} from '@/types';

export const INITIAL_CLINIC_SETTINGS: ClinicSettings = {
  clinicName: 'Tooth Story Dental Clinic',
  tagline: 'Gentle, World-Class Dental Care in Electronic City',
  phone: '090369 40356',
  whatsappNumber: '9036940356',
  address:
    'Malligue Residency, 16th Cross Road, Neeladri Nagar, Electronic City Phase I, Doddathoguru, Karnataka 560100',
  plusCode: 'RJRW+C3 Doddathoguru',
  landmark: 'Near Wipro Gate 5 & Ajmera Infinity, Neeladri Road',
  operatingHours: '9:00 AM – 10:00 PM (All 7 Days Open)',
  emergencyNote: 'Emergency on-call coverage available till late evening',
  googleMapsUrl:
    'https://maps.google.com/?q=Tooth+Story+Dental+Clinic+Neeladri+Nagar+Electronic+City',
  googleRating: 4.9,
  googleReviewsCount: 480,
};

export const INITIAL_DOCTORS: Doctor[] = [
  {
    id: 'dr-dhanashree',
    name: 'Dr. Dhanashree',
    designation: 'Chief Dental Surgeon & Endodontist',
    qualification: 'BDS, MDS (Conservative Dentistry & Endodontics)',
    specialties: ['Microscopic Root Canal', 'Cosmetic Restorations', 'Painless Anesthesia', 'Laser Dentistry'],
    experienceYears: 12,
    patientsTreated: '3,200+',
    rating: 4.9,
    reviewsCount: 360,
    photo:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuCM3Rl5_qDycg5MzurdHAxFuAje-whutR9iKPsv3hzzvYNQUYYhXeuCCUlSiwgk-L-EWIvyP4BSOTXd0JfRIIa6_I4A7UIyFOh6dpuOUOo3eIdipNCFlMO3XBlT3UdisGUDch0gl4zk2vHZbQh_lZfkCOZ4dKcLqdy9gCsI-v7Pp8z-75tHoKhX1I_T25umK7r7Zi_z8c898nzWOM2kdegvm9JPn35Qnpr2hoxd_JaYVG1pv23erfnATQ',
    bio: 'Dr. Dhanashree brings over a decade of clinical excellence in micro-endodontics and aesthetic dentistry. Known for her gentle chairside manner, she focuses on anxiety-free, zero-pain dental treatments utilizing modern computerized rotary techniques.',
    chairAssignment: 'Chair 1 & 2',
    availableDays: 'Monday – Sunday',
    shiftHours: '09:00 AM – 02:00 PM, 05:00 PM – 10:00 PM',
    active: true,
  },
  {
    id: 'dr-anand',
    name: 'Dr. Anand',
    designation: 'Consultant Orthodontist & Implantologist',
    qualification: 'BDS, MDS (Orthodontics & Dentofacial Orthopedics)',
    specialties: ['Clear Aligners', 'Self-Ligating Braces', 'Dental Implants', 'Surgical Extractions'],
    experienceYears: 10,
    patientsTreated: '2,400+',
    rating: 4.9,
    reviewsCount: 220,
    photo:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuBggQvQaQanLBY4HYRI03lflWviQkSmLO3JOMgsxy7RbpINpkG-d9IJQq1QfwwyAtLiBLtC5j1297Fk3XL2O1rc4mbo5r5toLuTKk7WLmPYgzrmAtk9HuABAQvsY4u88WpH2a08n4NI31W2zAPDnEZ9lMwO6Pcxtr0o-uSnY7wxvLyjaPZ1OC7VccL44nx-lV_kAjzYoZNIZXWjA7n_bXy4qT6ghqKuVFTHKtGlcIlYvdzzv29U09xz2g',
    bio: 'Specializing in adult and teen smile transformations, Dr. Anand integrates 3D digital planning for precise alignment using invisible aligners and durable osseointegrated dental implants.',
    chairAssignment: 'Chair 3',
    availableDays: 'Tuesday, Thursday, Saturday, Sunday',
    shiftHours: '04:00 PM – 09:30 PM',
    active: true,
  },
];

export const INITIAL_TREATMENTS: Treatment[] = [
  {
    id: 'root-canal-treatment',
    name: 'Root Canal Treatment',
    slug: 'root-canal-treatment',
    shortDescription:
      'Advanced single or dual sitting rotary endodontics with micro-apex locator precision and computer-guided local anesthesia.',
    description:
      'Our rotary root canal treatment removes infection while preserving your natural tooth structure. Utilizing electronic apex locators and flexible nickel-titanium files, the procedure is completed with minimal discomfort and utmost precision in a sterile environment.',
    category: 'Restorative & Endodontics',
    startingPrice: 3500,
    priceDisplay: 'Starting from ₹3,500',
    durationMinutes: 45,
    image:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuDJn7KOXqyuoUjo4OyMhhKXJUobSBWUvII87-lfut3jAKBGxQaE0QqKK2EDRXKqJIuJhSqD_Ik7QR-Zfsp7cbGrhJ-FwgPz4pCIYjEbf_zCq3trqCtPCgXmVIdO6bE9-JQ9eNSUsayJkVRBFgiHnHhmStms4vMz_wTBaFX3--MXM0GrgBiLVjIYuerzuM2Kl1h6u99ufazkT2sKsPD88DFTjKh71YUAdUQhGUnIJ1S29uIx5_OjClWWxw',
    icon: 'medical_services',
    badge: 'Painless Rotary',
    featured: true,
    active: true,
    benefits: [
      'Preserves natural tooth structure and jawbone density',
      'Rotary endodontics ensures faster, quieter procedure',
      'Single or two-sitting options depending on infection stage',
      'Digital RVG X-Rays with 90% reduced radiation',
    ],
    procedureSteps: [
      {
        step: 1,
        title: 'Digital Diagnostics & Local Numbing',
        description: 'High-definition digital periapical scan to pinpoint infection depth, followed by painless computerized anesthesia.',
      },
      {
        step: 2,
        title: 'Precision Canal Debridement',
        description: 'Gentle rotary files clean the pulp chamber and canals, sterilizing bacteria with ultrasonic irrigation.',
      },
      {
        step: 3,
        title: 'Biocompatible 3D Obturation & Sealing',
        description: 'Canals are hermetically sealed with gutta-percha to prevent reinfection, capped with composite restoration.',
      },
    ],
    faqs: [
      {
        question: 'Is root canal treatment painful at Tooth Story?',
        answer: 'Modern rotary endodontics combined with localized anesthesia ensures the treatment feels no different from receiving a standard dental filling.',
      },
      {
        question: 'How many visits are required?',
        answer: 'Most uncomplicated cases are completed in a single 45-minute sitting. Severe infections may require two appointments for optimal medicinal dressing.',
      },
      {
        question: 'Will I need a crown after the root canal?',
        answer: 'A crown is strongly recommended for premolars and molars to restore full chewing strength and protect the tooth from future fractures.',
      },
    ],
  },
  {
    id: 'wisdom-tooth-extraction',
    name: 'Wisdom Tooth Extraction',
    slug: 'wisdom-tooth-extraction',
    shortDescription:
      'Surgical and non-surgical third molar removal handled with gentle oral surgery methods to ensure quick 24-hr recovery.',
    description:
      'Impacted or misaligned wisdom teeth can cause severe throbbing pain, food trapping, and adjacent tooth damage. Our experienced surgeons remove impacted teeth with gentle elevation techniques, minimizing bone trauma for a fast recovery.',
    category: 'Oral Surgery',
    startingPrice: 2500,
    priceDisplay: 'Starting from ₹2,500',
    durationMinutes: 40,
    image:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuBvvttDmNuNM8ZGhu9RZHO3Tp8_uNX0qFO3o2Vt7jEbnuWS2om-TzU4hoCKJQjITzgRzW0hcQgB_AC0ckHBhAxiu1DWiSWDyxOAtzAnaYDJMWgqcRRqllJ3swgISVzdIZgToKI_j8V2y_Zl2AKqgtHcF8AOIMU3doOPZkic3FMXn-qN2T1vo4-Z0v0oZShymtR4S3caWtuzvXwKkIw6rUBR3pvbWRpQe5k6nV-Z0XBpgH-9u23uGF9J7g',
    icon: 'healing',
    badge: 'Minimally Invasive',
    featured: true,
    active: true,
    benefits: [
      'Relieves acute posterior jaw pain and recurring swelling',
      'Protects adjacent second molars from decay and resorption',
      'Minimally invasive technique for minimal post-op discomfort',
      'Detailed post-op medication and WhatsApp support guide',
    ],
    procedureSteps: [
      {
        step: 1,
        title: '3D Angulation Assessment',
        description: 'OPG imaging to inspect proximity to the inferior alveolar nerve and determine root anatomy.',
      },
      {
        step: 2,
        title: 'Gentle Controlled Elevation',
        description: 'Careful sectioning and removal of the third molar under complete local anesthesia.',
      },
      {
        step: 3,
        title: 'Hemostatic Dressing & Suturing',
        description: 'Dissolvable sutures placed where necessary with cold pack application for swift healing.',
      },
    ],
    faqs: [
      {
        question: 'When can I resume work after extraction?',
        answer: 'Most patients return to desk work and normal routines the next day. We provide complete post-op guidelines on WhatsApp.',
      },
      {
        question: 'Do all wisdom teeth require extraction?',
        answer: 'No, only third molars that are impacted, decayed, causing pain, or crowding adjacent teeth need removal.',
      },
    ],
  },
  {
    id: 'invisible-braces-aligners',
    name: 'Invisible Braces & Aligners',
    slug: 'invisible-braces-aligners',
    shortDescription:
      'Custom clear aligners and metal/ceramic brackets by Orthodontist Dr. Anand with 3D digital outcome preview.',
    description:
      'Straighten crooked teeth, close gaps, and correct bite issues discreetly. From US-certified clear aligners to aesthetic ceramic braces, our customized orthodontic plans deliver functional harmony and balanced facial aesthetics.',
    category: 'Orthodontics',
    startingPrice: 35000,
    priceDisplay: 'Starting from ₹35,000',
    durationMinutes: 30,
    image:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuDymdUnAIqw4XrHPcPKCq7rwJ1_1c2vit0vogCULnfub7fLMND23_9GthoXlDOEgVXqsiCKCsc3CmLilSCiLBqwsdquTCdMZy99YK2YmCVVSUfVIf2hjt9mNI1bdNMcO3xqw9Rcuqra97SHJdLbN2opdBHngnwYqiLBwZXzf6pciNIb8hhY1pHLMvVXWrc1Z4zNU8j-UOItws3PuVJ4UHWAgWne9vHt_3RwBfbuD8lavG6AReYUB1ZOxg',
    icon: 'view_in_ar',
    badge: '3D Digital Scan',
    featured: true,
    active: true,
    benefits: [
      'Virtually invisible trays with no dietary restrictions',
      '3D video simulation showing final smile before starting',
      'Flexible 0% interest monthly installment plans available',
      'Fewer clinic visits compared to traditional wire braces',
    ],
    procedureSteps: [
      {
        step: 1,
        title: 'Digital Intraoral 3D Scanning',
        description: 'Precise 3D optical scan of your teeth without messy putty impressions.',
      },
      {
        step: 2,
        title: 'Custom Orthodontic Simulation',
        description: 'Dr. Anand designs your step-by-step tooth movement plan, reviewed together on-screen.',
      },
      {
        step: 3,
        title: 'Aligner Delivery & Periodic Check-ins',
        description: 'Receive custom aligner sets changed every 10-14 days with brief monthly reviews.',
      },
    ],
    faqs: [
      {
        question: 'How long does clear aligner treatment take?',
        answer: 'Minor alignment cases take 4 to 8 months, while moderate to complex cases usually take 10 to 14 months.',
      },
      {
        question: 'Can I eat normally with clear aligners?',
        answer: 'Yes! Aligners are removable, so you take them out while eating and brush before putting them back on.',
      },
    ],
  },
  {
    id: 'teeth-cleaning-polishing',
    name: 'Teeth Cleaning & Polishing',
    slug: 'teeth-cleaning-polishing',
    shortDescription:
      'Ultrasonic scaling to remove stubborn tartar, coffee/smoking stains, paired with mineral enamel polishing.',
    description:
      'Maintain peak oral hygiene and healthy pink gums. Our ultrasonic cleaning gently vibrates plaque and hardened calculus away from enamel without scratching, finished with air-flow polishing for a luminous clean feel.',
    category: 'Preventive Care',
    startingPrice: 1200,
    priceDisplay: 'Starting from ₹1,200',
    durationMinutes: 30,
    image:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuDJn7KOXqyuoUjo4OyMhhKXJUobSBWUvII87-lfut3jAKBGxQaE0QqKK2EDRXKqJIuJhSqD_Ik7QR-Zfsp7cbGrhJ-FwgPz4pCIYjEbf_zCq3trqCtPCgXmVIdO6bE9-JQ9eNSUsayJkVRBFgiHnHhmStms4vMz_wTBaFX3--MXM0GrgBiLVjIYuerzuM2Kl1h6u99ufazkT2sKsPD88DFTjKh71YUAdUQhGUnIJ1S29uIx5_OjClWWxw',
    icon: 'clean_hands',
    badge: 'Ultrasonic Air-Flow',
    featured: true,
    active: true,
    benefits: [
      'Prevents gum bleeding, gingivitis, and periodontitis',
      'Removes stubborn tea, coffee, and tobacco stains',
      'Eliminates bad breath (halitosis) bacteria',
      'Recommended every 6 months for optimal oral health',
    ],
    procedureSteps: [
      {
        step: 1,
        title: 'Gingival Health Screening',
        description: 'Assessment of gum pockets and plaque deposit distribution.',
      },
      {
        step: 2,
        title: 'Piezoelectric Ultrasonic Scaling',
        description: 'Micro-vibrations flush calculus from subgingival and interdental zones.',
      },
      {
        step: 3,
        title: 'Micro-Fine Paste Polishing',
        description: 'Gentle mineral polish leaves tooth surfaces silky and stain-resistant.',
      },
    ],
    faqs: [
      {
        question: 'Does teeth cleaning make teeth loose or sensitive?',
        answer: 'No. Scaling only removes harmful tartar deposits that cause bone loss. Mild sensitivity disappears within 24 hours.',
      },
    ],
  },
  {
    id: 'ceramic-zirconia-crowns',
    name: 'Ceramic Zirconia Crowns',
    slug: 'ceramic-zirconia-crowns',
    shortDescription:
      'Metal-free, CAD/CAM milled natural-shade crowns and bridges with exceptional strength and 10-year warranty.',
    description:
      'Restore broken or root canal treated teeth with precision-milled Zirconia crowns. Metal-free and bio-compatible, they mimic the natural translucency of tooth enamel while delivering superior durability.',
    category: 'Prosthodontics',
    startingPrice: 6000,
    priceDisplay: 'Starting from ₹6,000',
    durationMinutes: 45,
    image:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuBvvttDmNuNM8ZGhu9RZHO3Tp8_uNX0qFO3o2Vt7jEbnuWS2om-TzU4hoCKJQjITzgRzW0hcQgB_AC0ckHBhAxiu1DWiSWDyxOAtzAnaYDJMWgqcRRqllJ3swgISVzdIZgToKI_j8V2y_Zl2AKqgtHcF8AOIMU3doOPZkic3FMXn-qN2T1vo4-Z0v0oZShymtR4S3caWtuzvXwKkIw6rUBR3pvbWRpQe5k6nV-Z0XBpgH-9u23uGF9J7g',
    icon: 'diamond',
    badge: '10-Year Warranty',
    featured: true,
    active: true,
    benefits: [
      '100% metal-free, no dark gum lines over time',
      'Custom CAD/CAM digital shade matching for seamless appearance',
      'High fracture resistance suitable for heavy molar biting',
      'Certified authentic laboratory warranty certificate provided',
    ],
    procedureSteps: [
      {
        step: 1,
        title: 'Precision Tooth Preparation',
        description: 'Conservative shaping under magnification for maximum crown retention.',
      },
      {
        step: 2,
        title: '3D Optical Digital Scan',
        description: 'Optical scan sent directly to German CAD/CAM milling robotics.',
      },
      {
        step: 3,
        title: 'Adhesive Cementation',
        description: 'Permanent resin bonding with perfect bite balance and occlusion check.',
      },
    ],
    faqs: [
      {
        question: 'How long do Zirconia crowns last?',
        answer: 'With standard oral hygiene and regular dental checkups, Zirconia crowns typically last 15+ years and come with a 10-year warranty.',
      },
    ],
  },
  {
    id: 'pediatric-dental-care',
    name: 'Pediatric Dental Care',
    slug: 'pediatric-dental-care',
    shortDescription:
      'Fluoride treatments, cavity protection sealants, and gentle restorations in a warm, child-friendly environment.',
    description:
      'We make dental visits enjoyable and stress-free for kids. From preventive fluoride varnish and pit/fissure sealants to gentle fillings, our warm team builds lasting positive oral habits for your little ones.',
    category: 'Pediatric Dentistry',
    startingPrice: 800,
    priceDisplay: 'Starting from ₹800',
    durationMinutes: 30,
    image:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuDymdUnAIqw4XrHPcPKCq7rwJ1_1c2vit0vogCULnfub7fLMND23_9GthoXlDOEgVXqsiCKCsc3CmLilSCiLBqwsdquTCdMZy99YK2YmCVVSUfVIf2hjt9mNI1bdNMcO3xqw9Rcuqra97SHJdLbN2opdBHngnwYqiLBwZXzf6pciNIb8hhY1pHLMvVXWrc1Z4zNU8j-UOItws3PuVJ4UHWAgWne9vHt_3RwBfbuD8lavG6AReYUB1ZOxg',
    icon: 'child_care',
    badge: 'Zero Anxiety Room',
    featured: true,
    active: true,
    benefits: [
      'Child-friendly communication preventing dental phobia',
      'Protective pit & fissure sealants to prevent deep cavities',
      'Enamel-strengthening remineralization fluoride treatments',
      'Gentle tooth-colored composite restorations',
    ],
    procedureSteps: [
      {
        step: 1,
        title: 'Friendly Tell-Show-Do Introduction',
        description: 'Interactive demonstration to make the child comfortable and relaxed.',
      },
      {
        step: 2,
        title: 'Gentle Preventive Cleaning / Restoration',
        description: 'Non-invasive, fast treatment using kid-safe dental tools.',
      },
      {
        step: 3,
        title: 'Reward & Oral Hygiene Coaching',
        description: 'Fun brushing demonstration with a complimentary bravery badge.',
      },
    ],
    faqs: [
      {
        question: 'At what age should my child first visit the dentist?',
        answer: 'The Indian Dental Association recommends the first dental visit by age 1 or when the first milk tooth erupts.',
      },
    ],
  },
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: 'rev-1',
    author: 'Aksa Johnson',
    initials: 'AJ',
    rating: 5,
    date: '3 weeks ago',
    treatment: 'Braces & Orthodontics',
    location: 'Electronic City Phase 1',
    comment:
      'I completed my braces treatment at this clinic, and my entire experience was smooth and hassle-free from start to finish. Dr. Dhanashree and Dr. Anand were always welcoming, supportive, and guided me properly throughout the process. Highly recommend Tooth Story!',
    verified: true,
    source: 'google',
  },
  {
    id: 'rev-2',
    author: 'Swarnali Basu',
    initials: 'SB',
    rating: 5,
    date: '1 month ago',
    treatment: 'Wisdom Tooth Extraction',
    location: 'Neeladri Nagar',
    comment:
      'I recently had my wisdom teeth extraction done from this clinic. And I must say I am so happy and grateful to all the doctors. Efficient, friendly, and helpful. No pain at all during and after the procedure!',
    verified: true,
    source: 'google',
  },
  {
    id: 'rev-3',
    author: 'Shabnam P K',
    initials: 'SP',
    rating: 5,
    date: '2 months ago',
    treatment: 'Root Canal & Checkup',
    location: 'Local Guide, Doddathoguru',
    comment:
      'Highly professional, friendly and caring. They listened to my concerns patiently and took the time to explain my dental health condition clearly before starting the treatment. The clinic is spotless and modern.',
    verified: true,
    source: 'google',
  },
  {
    id: 'rev-4',
    author: 'Amit Sengupta',
    initials: 'AS',
    rating: 5,
    date: '2 months ago',
    treatment: 'Teeth Cleaning & Crown',
    location: 'Electronic City',
    comment:
      'Visited for ultrasonic scaling and a zirconia crown. Zero waiting time, transparent pricing, and Dr. Dhanashree explained every step on the monitor. Outstanding care for techies living nearby.',
    verified: true,
    source: 'google',
  },
  {
    id: 'rev-5',
    author: 'Priyanka Nair',
    initials: 'PN',
    rating: 5,
    date: '3 months ago',
    treatment: 'Pediatric Care for Kids',
    location: 'Electronic City Phase 1',
    comment:
      'Took my 6-year-old daughter for her first cavity filling. The doctors were exceptionally gentle and patient. She did not cry at all and actually had fun! Truly the best dental clinic in Electronic City.',
    verified: true,
    source: 'google',
  },
];

export const INITIAL_GALLERY: GalleryItem[] = [
  {
    id: 'gal-1',
    title: 'Sterile Operatory Suite 01',
    category: 'operatory',
    imageUrl:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuDJn7KOXqyuoUjo4OyMhhKXJUobSBWUvII87-lfut3jAKBGxQaE0QqKK2EDRXKqJIuJhSqD_Ik7QR-Zfsp7cbGrhJ-FwgPz4pCIYjEbf_zCq3trqCtPCgXmVIdO6bE9-JQ9eNSUsayJkVRBFgiHnHhmStms4vMz_wTBaFX3--MXM0GrgBiLVjIYuerzuM2Kl1h6u99ufazkT2sKsPD88DFTjKh71YUAdUQhGUnIJ1S29uIx5_OjClWWxw',
    description: 'Fully automated ergonomic dental unit with computerized rotary endodontics and integrated HD intraoral camera.',
    badge: 'Class-B Autoclaved',
  },
  {
    id: 'gal-2',
    title: 'Welcoming Reception Lounge',
    category: 'lounge',
    imageUrl:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuDymdUnAIqw4XrHPcPKCq7rwJ1_1c2vit0vogCULnfub7fLMND23_9GthoXlDOEgVXqsiCKCsc3CmLilSCiLBqwsdquTCdMZy99YK2YmCVVSUfVIf2hjt9mNI1bdNMcO3xqw9Rcuqra97SHJdLbN2opdBHngnwYqiLBwZXzf6pciNIb8hhY1pHLMvVXWrc1Z4zNU8j-UOItws3PuVJ4UHWAgWne9vHt_3RwBfbuD8lavG6AReYUB1ZOxg',
    description: 'Calming, hospitable patient waiting lounge designed to eliminate dental anxiety with air purification.',
    badge: 'Anxiety-Free Zone',
  },
  {
    id: 'gal-3',
    title: 'High-Definition Digital Radiography (RVG)',
    category: 'technology',
    imageUrl:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuBvvttDmNuNM8ZGhu9RZHO3Tp8_uNX0qFO3o2Vt7jEbnuWS2om-TzU4hoCKJQjITzgRzW0hcQgB_AC0ckHBhAxiu1DWiSWDyxOAtzAnaYDJMWgqcRRqllJ3swgISVzdIZgToKI_j8V2y_Zl2AKqgtHcF8AOIMU3doOPZkic3FMXn-qN2T1vo4-Z0v0oZShymtR4S3caWtuzvXwKkIw6rUBR3pvbWRpQe5k6nV-Z0XBpgH-9u23uGF9J7g',
    description: 'Ultra-low radiation digital sensor providing instant crystal-clear canal mapping and diagnosis.',
    badge: '90% Less Radiation',
  },
  {
    id: 'gal-4',
    title: 'Doctor Consultation Operatory 02',
    category: 'operatory',
    imageUrl:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuCmC__NFtBHez3hUsFcPImG8L_X0_7MysXl21vCxUVUZy-z53ge4dczg9_dfEOX5isK4WA52TgntNKLhF83QBxfnJlsM0sYYztW5XvR39R2_UJFgk0_ZqgpjHpq-yuGccRYCzkMDBejzUVny22-2XV5fD1FYixhn253SqoYU5bp4SSEdDrWHY1LtxoFFWZwoogKNU5XsCC_CA-WuppCMIasgRr8It_TCbkAAZiZZYlo5XDhkFgAr1BIgw',
    description: 'Dedicated consult and pediatric care operatory equipped with gentle anesthesia delivery.',
    badge: 'Pediatric & Ortho Bay',
  },
];

export const INITIAL_APPOINTMENTS: Appointment[] = [
  {
    id: 'TS-EC-8942',
    clinicId: 'tooth-story-ecity',
    patientName: 'Pooja Sharma',
    phone: '9876543210',
    email: 'pooja.sharma@example.com',
    treatmentId: 'root-canal-treatment',
    treatmentName: 'Root Canal Treatment',
    preferredDate: '2026-10-02',
    preferredTime: '06:00 PM',
    timeSlotCategory: 'evening',
    message: 'Mild pain in upper left molar when drinking cold water.',
    status: 'pending',
    source: 'website',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    assignedDoctor: 'Dr. Dhanashree',
    operatoryBay: 'Operatory 02',
    estimatedFee: 3500,
  },
  {
    id: 'TS-EC-8943',
    clinicId: 'tooth-story-ecity',
    patientName: 'Priya Menon',
    phone: '9845012345',
    treatmentId: 'wisdom-tooth-extraction',
    treatmentName: 'Wisdom Tooth Extraction (Urgent)',
    preferredDate: '2026-10-01',
    preferredTime: '07:00 PM',
    timeSlotCategory: 'evening',
    message: 'Severe throbbing pain in lower jaw since morning.',
    status: 'pending',
    source: 'whatsapp',
    createdAt: new Date(Date.now() - 3600000).toISOString(),
    updatedAt: new Date().toISOString(),
    assignedDoctor: 'Dr. Anand',
    operatoryBay: 'Operatory 01',
    estimatedFee: 2500,
  },
  {
    id: 'TS-EC-8940',
    clinicId: 'tooth-story-ecity',
    patientName: 'Rohan Das',
    phone: '9741288219',
    treatmentId: 'invisible-braces-aligners',
    treatmentName: 'Braces Consultation & 3D Scan',
    preferredDate: '2026-10-02',
    preferredTime: '05:30 PM',
    timeSlotCategory: 'evening',
    status: 'confirmed',
    source: 'website',
    createdAt: new Date(Date.now() - 7200000).toISOString(),
    updatedAt: new Date().toISOString(),
    confirmedAt: new Date(Date.now() - 3600000).toISOString(),
    assignedDoctor: 'Dr. Dhanashree',
    operatoryBay: 'Chair 1',
    estimatedFee: 500,
    notes: 'Patient requested ceramic brackets evaluation.',
  },
  {
    id: 'TS-EC-8938',
    clinicId: 'tooth-story-ecity',
    patientName: 'Shalini Nair',
    phone: '9611033452',
    treatmentId: 'teeth-cleaning-polishing',
    treatmentName: 'Teeth Cleaning & Polishing',
    preferredDate: '2026-10-03',
    preferredTime: '11:00 AM',
    timeSlotCategory: 'morning',
    status: 'confirmed',
    source: 'website',
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    confirmedAt: new Date(Date.now() - 43200000).toISOString(),
    assignedDoctor: 'Dr. Dhanashree',
    operatoryBay: 'Chair 2',
    estimatedFee: 1200,
  },
  {
    id: 'TS-EC-8935',
    clinicId: 'tooth-story-ecity',
    patientName: 'Vikram Reddy',
    phone: '9900177123',
    treatmentId: 'root-canal-treatment',
    treatmentName: 'Root Canal Session 2 (Crown Prep)',
    preferredDate: '2026-10-01',
    preferredTime: '04:00 PM',
    timeSlotCategory: 'afternoon',
    status: 'confirmed',
    source: 'admin',
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    updatedAt: new Date().toISOString(),
    confirmedAt: new Date(Date.now() - 86400000).toISOString(),
    assignedDoctor: 'Dr. Dhanashree',
    operatoryBay: 'Chair 1',
    estimatedFee: 3500,
    notes: 'Obturation complete, ready for crown impressions.',
  },
  {
    id: 'TS-EC-8930',
    clinicId: 'tooth-story-ecity',
    patientName: 'Rajesh Sharma',
    phone: '9876543211',
    treatmentId: 'ceramic-zirconia-crowns',
    treatmentName: 'Ceramic Zirconia Crown Fitting',
    preferredDate: '2026-10-01',
    preferredTime: '12:00 PM',
    timeSlotCategory: 'afternoon',
    status: 'completed',
    source: 'website',
    createdAt: new Date(Date.now() - 259200000).toISOString(),
    updatedAt: new Date().toISOString(),
    confirmedAt: new Date(Date.now() - 172800000).toISOString(),
    assignedDoctor: 'Dr. Dhanashree',
    operatoryBay: 'Chair 1',
    estimatedFee: 6000,
    notes: 'Crown cemented with high-bond resin, shade A2 match.',
  },
];

export const INITIAL_PATIENTS: Patient[] = [
  {
    id: 'pat-1',
    clinicId: 'tooth-story-ecity',
    name: 'Pooja Sharma',
    phone: '9876543210',
    email: 'pooja.sharma@example.com',
    createdAt: '2026-09-15T10:00:00.000Z',
    updatedAt: '2026-10-01T08:00:00.000Z',
    totalAppointments: 1,
    latestAppointmentDate: '2026-10-02',
    latestTreatment: 'Root Canal Treatment',
    status: 'active',
    notes: 'First-time patient from Neeladri Nagar.',
  },
  {
    id: 'pat-2',
    clinicId: 'tooth-story-ecity',
    name: 'Priya Menon',
    phone: '9845012345',
    createdAt: '2026-10-01T07:00:00.000Z',
    updatedAt: '2026-10-01T07:00:00.000Z',
    totalAppointments: 1,
    latestAppointmentDate: '2026-10-01',
    latestTreatment: 'Wisdom Tooth Extraction',
    status: 'active',
    notes: 'Urgent referral for third molar pericoronitis.',
  },
  {
    id: 'pat-3',
    clinicId: 'tooth-story-ecity',
    name: 'Rohan Das',
    phone: '9741288219',
    createdAt: '2026-08-20T11:30:00.000Z',
    updatedAt: '2026-10-01T09:00:00.000Z',
    totalAppointments: 3,
    latestAppointmentDate: '2026-10-02',
    latestTreatment: 'Braces Consultation & 3D Scan',
    status: 'active',
  },
  {
    id: 'pat-4',
    clinicId: 'tooth-story-ecity',
    name: 'Rajesh Sharma',
    phone: '9876543211',
    email: 'rajesh.sharma@example.com',
    createdAt: '2026-07-10T14:00:00.000Z',
    updatedAt: '2026-10-01T12:30:00.000Z',
    totalAppointments: 4,
    latestAppointmentDate: '2026-10-01',
    latestTreatment: 'Ceramic Zirconia Crown Fitting',
    status: 'active',
    notes: 'Completed RCT & Zirconia Crown for Upper Left Molar.',
  },
];
